### ISSUE TITLE
suds.WebFault: Server raised fault

### ISSUE THREAD

**Issue by mudx** [TransbankDevelopers/transbank-webpay-credenciales#11]
Hola amigos, quisiera hacerles una consulta.. despues de un dia entero buscando..les escribo para ver si me pueden ayudar con el siguiente error :

suds.WebFault: Server raised fault: Commerce connection type must be WS(277) 

el error se esta generando al momento de pagar con webpay en mi odoo version 11c.

Anterior a este tuve otros errores los cuales fui solucionando.. y llege al jefe final que es este.... alguien sabe como solucionarlo ??

**Comment by sebardo** [comment]
¿Como lo soluciuonaste? Saludos
