### ISSUE TITLE
Remove not existing product

### ISSUE THREAD

**Issue by nmella** [TransbankDevelopers/transbank-webpay-credenciales#13]
Hi guys,

I have requested the "**_Webpay Plus Mall - Captura Diferida CLP_**" product to the Transbank callcenter staff, and they have replied that this product does not exist in their portfolio products.  I have called several times and spoke to different representatives, and they insist that this product is not available. 

If the product does not exist, please **remove** all the associate documentation and certificates. We have spent several hours integrating this solution, to finally knowing that it does not exist. 

Please remove this section;

[TransbankDevelopers/transbank-webpay-credenciales/Webpay Plus Mall - Captura Diferida CLP](https://github.com/TransbankDevelopers/transbank-webpay-credenciales/tree/master/integracion/Webpay%20Plus%20Mall%20-%20Captura%20Diferida%20CLP)

Just as reference, here is our integration screenshot:

![image](https://user-images.githubusercontent.com/5648244/82470639-993cf380-9a93-11ea-8fe1-58b367abd10f.png)

**Comment by gdespirito** [comment]
I will ask about what they told you, but if there are commerces with that integration already made (maybe years ago) we should not remove this documentation.

**Comment by nmella** [comment]
They explicitly said: 

Maryannys I.:  
> Con respecto a el contrato según me indicaron para Webpay Tienda Mall no permite captura diferida.
>Don Nicolas le adjunto capturas de los 2 modelos de contrato para Webpay. La primera imagen pertenece a un Webpay Plus con carro de compra que da la opcion de captura diferida, la segunda pertenece al contrato de Webpay Plus Tienda Mall que es el solicitado por el comercio que solamente da la opcion de captura sumultánea.
>![2](https://user-images.githubusercontent.com/5648244/82472199-cdb1af00-9a95-11ea-9d77-56556b320b28.jpg)
>![3](https://user-images.githubusercontent.com/5648244/82472206-d1453600-9a95-11ea-92f9-9a35887ee15a.jpg)

**Comment by gdespirito** [comment]
Hola! ¿Lograste realizar la contratación del producto o definitivamente te comentaron que ya no existe? Acabo de retomar esto y te cuento que noticis tengo por mi lado.

**Comment by nmella** [comment]
Hola @gonzunigad 

Sí, hicimos el contrato finalmente. Un ejecutivo nos ayudó a "conseguir" el contracto correcto.

Gracias.
