### ISSUE TITLE
Problema con credenciales Webpay Plus Mall - CLP 

### ISSUE THREAD

**Issue by guidopontet** [TransbankDevelopers/transbank-webpay-credenciales#15]
Hace unos meses (incluso años), tenía configurado un server en entorno de `staging` para las pruebas, con las credenciales de Webpay Plus Mall - CLP y con las tiendas establecidas correctamente para las pruebas, tal cual se indican en la [documentación](https://github.com/TransbankDevelopers/transbank-webpay-credenciales/tree/master/integracion/Webpay%20Plus%20Mall%20-%20CLP).

Sin embargo, hace unos días, al momento de desasociar la tienda del mall y volver a asociarla, obtengo un `rejected`, indicando que el código de comercio no es válido. Insisto en el punto en que no hay cambio de código de mi parte ni de credenciales, por lo que me resta preguntar si siguen siendo válidos códigos de comercio asociados al mall, presentes en la documentación:
  - 597044444402
  - 597044444403

Gracias

**Comment by ffiebig** [comment]
Hola, SOAP está siendo dado de baja. Algunas credenciales ya no funcionan y debido a eso
