### ISSUE TITLE
PatPass Integration Certificates

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-webpay-credenciales#3]
It's not documented on the official API, but at least on the [PHP SDK there is a function to test PatPass with an unique commerce code](https://github.com/DarkGhostHunter/transbank-sdk-php/blob/master/lib/webpay/configuration.php#L325).

I tried to find the credentials here to no avail.

It PatPass supported, or this repo need to add these files?

**Comment by leosoto** [comment]
I think the credentials in the SDKs are outdated (libwebpay got them as a non documented feature some time ago) and no new official credentials have been issued. As soon as we get them we'll certainly add them to this repo (so feel free to watch this repo to be among the first to know!)

**Comment by DarkGhostHunter** [comment]
Update on things?

**Comment by leosoto** [comment]
No news, but we should get some patpass credentials during December (I hope)

**Comment by leosoto** [comment]
Well, I might have been too optimistic. ThingsHaveHappend® and people have been busy putting fires off.  So the certificate creation (which is easy) and validation/testing (not so easy[1])have not happened during December and I'm not going to bet it will happen. 

But it *is* on the pipeline and as long as not many fires appear we should at least get credentials soon-ish. (Docs and official SDK will take some additionals weeks/months after the credentials are released, of course)

[1] There are no official tools yet for PatPass to plug credentials and play (as it happens with Webpay or Onepay) so the Transbank team has to test/troubleshoot things by hand (with SOAP UI and things like that I guess).

**Comment by DarkGhostHunter** [comment]
I understand. I hope for the best.

I will leave this open until Patpass credentials arrive.
